### ISSUE TITLE
ERROR -Altay 3.0.6

### ISSUE THREAD

**Issue by ghost** [FutureDeveloperZ/EconomyAPIUI#1]
10:33:16 CRITICAL > 이벤트 'pocketmine\event\server\DataPacketReceiveEvent'을(를) 'FormAPI v1.2.0'에 전달할 수 없습니다: jojoe77777\FormAPI\FormAPI에서의 Argument 2 passed to Wolf\Main::Wolf\{closure}() must be of the type array, null given, called in C:\Users\ghkst\Desktop\Altay-master\plugins\FormAPI-master\src\jojoe77777\FormAPI\FormAPI.php on line 75
10:33:16 CRITICAL > TypeError: "Argument 2 passed to Wolf\Main::Wolf\{closure}() must be of the type array, null given, called in C:\Users\ghkst\Desktop\Altay-master\plugins\FormAPI-master\src\jojoe77777\FormAPI\FormAPI.php on line 75" (EXCEPTION) in "EconomyAPIUI-master/src/Wolf/Main" at line 31
10:33:16 DEBUG > #0 FormAPI-master/src/jojoe77777/FormAPI/FormAPI(75): Wolf\Main->Wolf\{closure}(pocketmine\Player object, NULL )
10:33:16 DEBUG > #1 src/pocketmine/plugin/MethodEventExecutor(38): jojoe77777\FormAPI\FormAPI->onPacketReceived(pocketmine\event\server\DataPacketReceiveEvent object)
10:33:16 DEBUG > #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(jojoe77777\FormAPI\FormAPI object, pocketmine\event\server\DataPacketReceiveEvent object)
10:33:16 DEBUG > #3 src/pocketmine/plugin/PluginManager(753): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
10:33:16 DEBUG > #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(100): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
10:33:16 DEBUG > #5 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
10:33:16 DEBUG > #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(101): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
10:33:16 DEBUG > #7 src/pocketmine/Player(3177): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
10:33:16 DEBUG > #8 src/pocketmine/network/mcpe/RakLibInterface(158): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
10:33:16 DEBUG > #9 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 58.121.136.40 60444, raklib\protocol\EncapsulatedPacket object, integer 0)
10:33:16 DEBUG > #10 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()
10:33:16 DEBUG > #11 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
10:33:16 DEBUG > #12 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
10:33:16 DEBUG > #13 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
10:33:16 DEBUG > #14 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
10:33:16 DEBUG > #15 src/pocketmine/Server(2323): pocketmine\snooze\SleeperHandler->sleepUntil(double 1535158996.9164)
10:33:16 DEBUG > #16 src/pocketmine/Server(2233): pocketmine\Server->tickProcessor()
10:33:16 DEBUG > #17 src/pocketmine/Server(1794): pocketmine\Server->start()
10:33:16 DEBUG > #18 src/pocketmine/PocketMine(241): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\ghkst\Desktop\Altay-master\, string C:\Users\ghkst\Desktop\Altay-master\plugins\)
10:33:16 DEBUG > #19 C:/Users/ghkst/Desktop/Altay-master/Altay.phar(1): require_once(string phar://C:/Users/ghkst/Desktop/Altay-master/Altay.phar/src/pocketmine/PocketMine.php)

**Comment by Wolfkid200444** [comment]
Sorry for you to hear this but we dont support *Altay*

**Comment by Wolfkid200444** [comment]
Only way to work is using **PocketMine**

**Comment by ghost** [comment]
Please update to Altay separately. It's a very very very necessary plugin for me.

**Comment by Wolfkid200444** [comment]
can't man
